parameters:
    redis.host: '%env(string:REDIS_HOST)%'
    redis.port: '%env(int:REDIS_PORT)%'
    redis.db: '%env(int:REDIS_DB)%'
    redis.namespace: '%env(string:REDIS_NAMESPACE)%'
    redis.ttl: '%env(int:REDIS_TTL)%'

framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: 'redis://%redis.host%:%redis.port%/%redis.db%'

        pools:
            challenge.cache:
                adapter: cache.adapter.redis
                provider: challenge.redis.provider
