version: '3.8'

services:
  challenge-api:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.api
    container_name: challenge-api
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
